version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/home/btc/node_modules
      - ./@types:/home/btc/@types
      - ./public:/home/btc/public
      - ./src:/home/btc/src
      - ./package.json:/home/btc/package.json
      - ./tsconfig.json:/home/btc/tsconfig.json
    env_file: ./docker.env
    networks:
      - btc-network
networks:
  btc-network:
